trigger:
  - master

pr:
  branches:
    include:
      - master

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - master
    always: true

jobs:
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: ci/azure-install-rust.yml
      - template: ci/azure-test-all.yml
    strategy:
      matrix:
        stable-x86_64-msvc:
          TOOLCHAIN: stable-x86_64-pc-windows-msvc
        # stable-x86_64-gnu:
        #  TOOLCHAIN: stable-x86_64-pc-windows-gnu
        # stable-i686-msvc:
        #   TOOLCHAIN: stable-i686-pc-windows-msvc
        # stable-i686-gnu:
        #   TOOLCHAIN: stable-i686-pc-windows-gnu

  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-install-rust.yml
      - template: ci/azure-test-all.yml
    strategy:
      matrix:
        stable-x86_64:
          TOOLCHAIN: stable-x86_64-unknown-linux-gnu
        # stable-i686:
        #   TOOLCHAIN: stable-i686-unknown-linux-gnu
        nightly-x86_64:
          TOOLCHAIN: nightly

  - job: MacOS
    pool:
      vmImage: macOS-10.14
    steps:
      - template: ci/azure-install-rust.yml
      - template: ci/azure-test-all.yml
    strategy:
      matrix:
        stable-x86_64:
          TOOLCHAIN: stable-x86_64-apple-darwin