[package]
name = "luajit2-sys"
version = "0.0.1"
authors = ["Aaron Loucks <aloucks@cofront.net>"]
edition = "2018"
keywords = ["lua", "luajit", "script"]

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0.40"
fs_extra = "1.1.0"
